/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package AppServer;

import static org.junit.Assert.assertEquals;

import java.util.ArrayList;
import java.util.List;

import org.junit.Test;

import appserver.model.Movie;
import appserver.model.TitleSearch;
import appserver.service.Transformer;

public class TransformerTest {
    @Test public void testTransformerResponseMethod() throws Exception {
    	
    	List<Movie> movies = new ArrayList<Movie>();
    	
    	String xmlParse = "";

    	String xml = "<TitleSearch>\n" + 
    			"  <title>winner</title>\n" + 
    			"  <movies>\n" + 
    			"    <found>\n" + 
    			"      <name>Winner</name>\n" + 
    			"      <year>2017</year>\n" + 
    			"    </found>\n" + 
    			"  </movies>\n" + 
    			"</TitleSearch>";
    	
    	Movie movie = new Movie();
		
    	movie.setName("Winner");

		movie.setYear("2017");
		
		movies.add(movie);
		
    	TitleSearch titleSearch = new TitleSearch("winner", movies);
		
		xmlParse = Transformer.layoutResponseXML(titleSearch);
		
		assertEquals(xml,xmlParse);
    	
    }
}
