/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package AppClient;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

import com.thoughtworks.xstream.XStream;
import com.thoughtworks.xstream.io.xml.DomDriver;

import appclient.model.Title;

public class TransformerTest {
	@Test
	public void testTransformerRequestMethod() {
		
		String xml = "<Title>\n" + 
				"  <reference>winner</reference>\n" + 
				"</Title>";
		
		String xmlParse = "";
		
		Title title = new Title();

		title.setReference("winner");

		XStream xstream = new XStream(new DomDriver());

		xstream.alias("Title", appclient.model.Title.class);

		xmlParse = xstream.toXML(title);

		assertEquals(xml,xmlParse);

	}
}
